# -*- coding: utf-8 -*-
"""Day15_Working_With_CSV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P61__cD7kYKwmqD34OIrliIUwlQ9-TEV

## 1.Importing Pandas

> Add blockquote
"""

import pandas as pd

"""## 2.Importing Local Csv File"""

df = pd.read_csv("/content/sales.csv")
df

"""## 3.Sep Parameter"""

df = pd.read_csv("/content/sales.csv",sep = ",")
df

"""4.Index_col Parameter"""

df = pd.read_csv("/content/sales.csv",index_col="sales_id")
df

"""## 5.Change the name of header"""

df = pd.read_csv("/content/sales.csv",names = ["sid","oid","pid","price","qunt","total_price"])
df  # use when the header of file is not available

"""## 6.Header Parameter

"""

pd.read_csv("/content/sales.csv",header = 0)
# 0 is defualt values
# 1 use when header consider as first row

"""## 7.Use_cols parameter"""

pd.read_csv("/content/sales.csv",usecols = ["order_id","product_id","price_per_unit","total_price"])

"""## 8.Squeeze parameter"""

pd.read_csv("/content/sales.csv",usecols = ["order_id"]).squeeze("columns")
#converted a single column DataFrame into a Series

"""## 9.skiprows/nrows Parameter"""

pd.read_csv("/content/sales.csv",skiprows = [2,5]) #skip the 2nd and 5th rows
pd.read_csv("/content/sales.csv",nrows =100) #give 100 rows of dataset

"""## 10.Encoding parameter"""

pd.read_csv("/content/sales.csv",encoding="unicode_escape")

"""##11.Skip Bad Line"""

pd.read_csv("/content/sales.csv",on_bad_lines= "error")  #skip the mistaken data rows

"""##12.Dtype parameter"""

pd.read_csv("/content/sales.csv",dtype = {"quantity":"float"}) #can change the column data type

"""## 13.Handling Dates

"""

pd.read_csv("/content/sales.csv",parse_dates= ['date']).info()

"""## 14.Convertor"""

def renumber(total_price):
  total_price = int(total_price)
  if total_price >= 200:
    return "200+"
  else:
    return "100+"
renumber(256)

pd.read_csv("/content/sales.csv",converters={"total_price":renumber})

"""## 15.Na_value parameter"""

pd.read_csv("/content/sales.csv",na_values=["2",])

"""## 16.Loading a Huge Dataset in chunks"""

df = pd.read_csv("/content/sales.csv",chunksize=500)

for i in df:
  print(i.shape)

#convert the large dataset into small parts

